imports:
    - { resource: parameters.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    # knp_menu.voter.router.class: Knp\Menu\Matcher\Voter\RegexVoter

    
framework:
    secret: %kernel.secret%
    # JMS\TranslationBundle\JMSTranslationBundle needs validation
    validation: ~
    templating:
        engines: ['twig']
    translator: { fallbacks: ['%locale%'], logging: false }    

twig:
    globals:
        slugify: "@cocur_slugify"
        
# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                host:     '%database.host%'
                port:     '%database.port%'
                dbname:   '%database.name%'
                user:     '%database.user%'
                password: '%database.password%'
                #driver:  pdo_mysql
                charset:  '%database.charset%' # UTF8
                options:
                        1002: "SET NAMES '%database.charset%' COLLATE '%database.charset%_unicode_ci'"
                default_table_options:
                    charset: %database.charset%
                    collate: '%database.charset%_unicode_ci'
                    engine:  MyISAM     # InnoDB
            admin:
                host:     '%database.host%'
                port:     '%database.port%'
                dbname:   'juedischegeschichte'
                user:     '%database.user%'
                password: '%database.password%'
                #driver:  pdo_mysql
                charset:  '%database.charset%' # UTF8
                options:
                        1002: "SET NAMES '%database.charset%' COLLATE '%database.charset%_unicode_ci'"
                default_table_options:
                    charset: %database.charset%
                    collate: '%database.charset%_unicode_ci'
                    engine:  MyISAM     # InnoDB
    orm:
        connection: default        
        auto_generate_proxy_classes: '%kernel.debug%'
        auto_mapping: true 

stof_doctrine_extensions:
    orm:
        default:
            timestampable: true

assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~
        # see http://symfony.com/doc/current/cookbook/assetic/php.html
        scssphp:
            formatter: 'Leafo\ScssPhp\Formatter\Compressed'
            
jms_i18n_routing:
    default_locale: de
    locales: [de, en]
    strategy: custom
    hosts:
        de: %jms_i18n_routing.hosts.de%
        en: %jms_i18n_routing.hosts.en%
    redirect_to_host: true
    
knp_menu:
    # use "twig: false" to disable the Twig extension and the TwigRenderer
    twig:
        template: knp_menu.html.twig
    #  if true, enables the helper for PHP templates
    templating: false
    # the renderer to use, list is also available by default
    default_renderer: twig
    
liip_url_auto_converter:
    linkclass:
    target: _blank
    debugmode: false